### ISSUE TITLE
Error thrown by Ghosts class when you die without an equipped weapon

### ISSUE THREAD

**Issue by victorysoftworks** [victorysoftworks/rogue#62]
```
TypeError: Cannot read property 'startsWith' of null
    at Ghosts.save (/Users/sersavictory/Documents/Rogue/exe/Rogue-darwin-x64/Rogue.app/Contents/Resources/app/Game/Ghosts.js:107:45)
    at _callee6$ (/Users/sersavictory/Documents/Rogue/exe/Rogue-darwin-x64/Rogue.app/Contents/Resources/app/Game/Game.js:1269:24)
    at tryCatch (/Users/sersavictory/Documents/Rogue/exe/Rogue-darwin-x64/Rogue.app/Contents/Resources/app/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/sersavictory/Documents/Rogue/exe/Rogue-darwin-x64/Rogue.app/Contents/Resources/app/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/Users/sersavictory/Documents/Rogue/exe/Rogue-darwin-x64/Rogue.app/Contents/Resources/app/node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/sersavictory/Documents/Rogue/exe/Rogue-darwin-x64/Rogue.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/sersavictory/Documents/Rogue/exe/Rogue-darwin-x64/Rogue.app/Contents/Resources/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

**Comment by victorysoftworks** [comment]
Happens when you have no weapon equipped!
